In [23]:
import pandas as pd
import numpy as np

In [24]:
dados_1sem = 'Preços semestrais - AUTOMOTIVOS_2025.01.csv'
df_1sem = pd.read_csv(dados_1sem, sep=';')
df_1sem.head(3)

C:\Users\maria.chan\AppData\Local\Temp\ipykernel_30288\3132973569.py:2: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Valor de Venda, 13: Unidade de Medida, 14: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_1sem = pd.read_csv(dados_1sem, sep=';')

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN

In [25]:
dados_2sem = 'Preços semestrais - AUTOMOTIVOS_2025.02.csv'
df_2sem = pd.read_csv(dados_2sem, sep=';')
#df_2sem = [coluna1.colunax, colunaz] - escolhemos colunas
df_2sem.head(3)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,4431113000100,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,DIESEL,01/07/2025,"6,69",NaN,R$ / litro,BRANCA
1,N,AP,MACAPA,SEPE TIARAJU EMPREENDIMENTOS LTDA,5297501000286,RUA SETENTRIONAL,S/N,ESQUINA COM BEIRA RIO,ARAXÁ,68903-640,DIESEL,01/07/2025,"6,33",NaN,R$ / litro,BRANCA
2,NE,BA,IPIRA,AUTO POSTO AUGUSTU'S LTDA,2448248000145,SITIO SAO JOSE,SN,NaN,SEDE,44600-000,DIESEL,01/07/2025,"6,9",NaN,R$ / litro,ALE

In [26]:
#concatenar arquivos
df_anp = pd.concat([df_1sem,df_2sem], ignore_index = True)   #concatenou 1o sem e 2o sem; ignora index para ignorar indices do 1o e 2o sem

In [27]:
#transformar números que estão com virgula/string para ponto/número para permitir cálculos posteriores
#após mudança para float, se rodar novamente, vai dar erro pois o número já é float e não string
df_anp['Valor de Venda'] = df_anp['Valor de Venda'].str.replace(',','.').astype(float)

In [28]:
df_gasolina = df_anp.loc[df_anp['Produto'] == 'GASOLINA']
df_etanol = df_anp.loc[df_anp['Produto'] == 'ETANOL']

In [29]:
#agrupar produto por estado para depois fazer os cálculos
df_media_est_gaso = df_gasolina.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index()  #grupando valor de venda calculando média

df_media_est_gaso = df_media_est_gaso.sort_values(by='Valor de Venda', ascending = False)  #grupando valor de venda calculando média
df_media_est_gaso

   Estado - Sigla  Valor de Venda
0              AC        7.671043
2              AM        7.226496
21             RR        6.947907
20             RO        6.914577
24             SE        6.547728
26             TO        6.534131
6              DF        6.442591
17             PR        6.427747
13             PA        6.401182
23             SC        6.393332
4              BA        6.390745
5              CE        6.373081
1              AL        6.331550
19             RN        6.330973
15             PE        6.330366
8              GO        6.291102
12             MT        6.260951
7              ES        6.256656
22             RS        6.222312
11             MS        6.206580
18             RJ        6.145133
10             MG        6.130570
9              MA        6.128841
25             SP        6.091283
14             PB        6.059165
3              AP        6.041904
16             PI        5.925385

In [30]:
df_media_est_gaso.head()

   Estado - Sigla  Valor de Venda
0              AC        7.671043
2              AM        7.226496
21             RR        6.947907
20             RO        6.914577
24             SE        6.547728

In [31]:
#agrupar produto por estado para depois fazer os cálculos
df_media_est_etanol = df_etanol.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index()  #grupando valor de venda calculando média

df_media_est_etanol = df_media_est_etanol.sort_values(by='Valor de Venda', ascending = False)  #grupando valor de venda calculando média
df_media_est_etanol

   Estado - Sigla  Valor de Venda
0              AC        5.450321
2              AM        5.429408
3              AP        5.428462
20             RO        5.213401
21             RR        5.164806
5              CE        5.115794
19             RN        4.999004
1              AL        4.974708
9              MA        4.944062
22             RS        4.873926
24             SE        4.853322
13             PA        4.840288
4              BA        4.787785
26             TO        4.773923
15             PE        4.772174
23             SC        4.741009
6              DF        4.641591
16             PI        4.625402
18             RJ        4.610375
7              ES        4.527789
14             PB        4.491290
17             PR        4.457752
8              GO        4.453903
10             MG        4.333693
12             MT        4.160479
25             SP        4.104169
11             MS        4.078334

In [32]:
df_media_est_etanol.head()

   Estado - Sigla  Valor de Venda
0              AC        5.450321
2              AM        5.429408
3              AP        5.428462
20             RO        5.213401
21             RR        5.164806

In [35]:
#comparação regional de preços gasolina
df_media_regiao_gasolina = df_gasolina.groupby('Regiao - Sigla')['Valor de Venda'].mean().reset_index()  #grupando valor de venda calculando média
df_media_regiao_gasolina

  Regiao - Sigla  Valor de Venda
0             CO        6.293839
1              N        6.716720
2             NE        6.288195
3              S        6.331845
4             SE        6.115093

In [ ]:
#comparação regional de preços etano
df_media_regiao_etanol = df_etanol.groupby('Regiao - Sigla')['Valor de Venda'].mean().reset_index()  #grupando valor de venda calculando média
df_media_regiao_etanol

  Regiao - Sigla  Valor de Venda
0             CO        4.352734
1              N        5.085354
2             NE        4.845289
3              S        4.629784
4             SE        4.237751

In [ ]:
#Preço médio por município