In [63]:
import pandas as pd
import numpy as np  # permite trabalhar estatistica

In [64]:
dados = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(dados, sep=';', encoding='latin1')

(df.head())

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [65]:
df.tail()    # retorna apenas o último comando de display

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,2.0,0.0,37,1,0,0,0,0,157,2
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,32,0,0,0,0,0,234,2
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,10.0,0.0,98,9,1,0,0,0,713,2
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,3.0,0.0,25,2,0,0,0,0,258,2
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0.0,0.0,3,0,0,0,0,0,57,2

In [66]:
df_furto_celular_cisp = df.groupby('cisp')['furto_celular'].sum().reset_index()  #qual o furto de celular por delegacia?
df_furto_celular_cisp

     cisp  furto_celular
0       1          15487
1       4          13700
2       5          23969
3       6           6410
4       7           1485
..    ...            ...
133   159            455
134   165           1233
135   166           2580
136   167            497
137   168            121

[138 rows x 2 columns]

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37314 entries, 0 to 37313
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        37314 non-null  int64
 1   mes                         37314 non-null  int64
 2   ano                         37314 non-null  int64
 3   mes_ano                     37314 non-null  str
 4   aisp                        37314 non-null  int64
 5   risp                        37314 non-null  int64
 6   munic                       37314 non-null  str
 7   mcirc                       37314 non-null  int64
 8   regiao                      37314 non-null  str
 9   hom_doloso                  37314 non-null  int64
 10  lesao_corp_morte            37314 non-null  int64
 11  latrocinio                  37314 non-null  int64
 12  cvli                        37314 non-null  int64
 13  hom_por_interv_policial     37314 non-null  int64
 14  feminicidio                 2192 non-null   float64
 15  letalidade_violenta         37314 non-null  int64
 16  tentat_hom                  37314 non-null  int64
 17  tentativa_feminicidio       2192 non-null   float64
 18  lesao_corp_dolosa           37314 non-null  int64
 19  estupro                     37314 non-null  int64
 20  hom_culposo                 37314 non-null  int64
 21  lesao_corp_culposa          37314 non-null  int64
 22  roubo_transeunte            37314 non-null  int64
 23  roubo_celular               37314 non-null  int64
 24  roubo_em_coletivo           37314 non-null  int64
 25  roubo_rua                   37314 non-null  int64
 26  roubo_veiculo               37314 non-null  int64
 27  roubo_carga                 37314 non-null  int64
 28  roubo_comercio              37314 non-null  int64
 29  roubo_residencia            37314 non-null  int64
 30  roubo_banco                 37314 non-null  int64
 31  roubo_cx_eletronico         37295 non-null  float64
 32  roubo_conducao_saque        37314 non-null  int64
 33  roubo_apos_saque            37314 non-null  int64
 34  roubo_bicicleta             19925 non-null  float64
 35  outros_roubos               37314 non-null  int64
 36  total_roubos                37314 non-null  int64
 37  furto_veiculos              37314 non-null  int64
 38  furto_transeunte            37314 non-null  int64
 39  furto_coletivo              37314 non-null  int64
 40  furto_celular               37314 non-null  int64
 41  furto_bicicleta             19925 non-null  float64
 42  outros_furtos               37314 non-null  int64
 43  total_furtos                37314 non-null  int64
 44  sequestro                   37314 non-null  int64
 45  extorsao                    37314 non-null  int64
 46  sequestro_relampago         37314 non-null  int64
 47  estelionato                 37314 non-null  int64
 48  apreensao_drogas            37314 non-null  int64
 49  posse_drogas                32668 non-null  float64
 50  trafico_drogas              32668 non-null  float64
 51  apreensao_drogas_sem_autor  32668 non-null  float64
 52  recuperacao_veiculos        37314 non-null  int64
 53  apf                         32668 non-null  float64
 54  aaapai                      32668 non-null  float64
 55  cmp                         32668 non-null  float64
 56  cmba                        32668 non-null  float64
 57  ameaca                      37314 non-null  int64
 58  pessoas_desaparecidas       37314 non-null  int64
 59  encontro_cadaver            37314 non-null  int64
 60  encontro_ossada             37314 non-null  int64
 61  pol_militares_mortos_serv   37314 non-null  int64
 62  pol_civis_mortos_serv       37314 non-null  int64
 63  registro_ocorrencias        37314 non-null  int64
 64  fase                        37314 non-null  int64
dtypes: float64(12), int64(50), str(3)
memory usage: 18.5 MB

In [68]:
df.describe()   #pega todas as colunas e dá as estatísticas - conta, média, min, 25%, 50%, 75%

,cisp,mes,ano,aisp,risp,mcirc,hom_doloso,lesao_corp_morte,latrocinio,cvli,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
count,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,3.731400e+04,37314.000000,37314.000000,37314.000000,37314.000000,...,32668.000000,32668.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000
mean,81.724259,6.482232,2014.188723,20.148470,3.869942,3.791939e+06,2.925256,0.028140,0.095380,3.048775,...,8.741306,0.641545,41.308731,3.223964,0.360481,0.022967,0.013400,0.002224,444.005306,2.985314
std,48.320410,3.461767,6.625316,11.348509,2.011450,1.741132e+06,4.327953,0.179516,0.366265,4.443058,...,14.809300,1.640367,39.390699,4.160668,0.988235,0.181215,0.130895,0.049334,398.542615,0.120295
min,1.000000,1.000000,2003.000000,1.000000,1.000000,3.300100e+06,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,38.000000,3.000000,2008.000000,10.000000,2.000000,3.302601e+06,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,106.000000,3.000000
50%,78.000000,6.000000,2014.000000,20.000000,4.000000,3.304557e+06,1.000000,0.000000,0.000000,1.000000,...,5.000000,0.000000,30.000000,2.000000,0.000000,0.000000,0.000000,0.000000,370.000000,3.000000
75%,125.000000,9.000000,2020.000000,30.000000,6.000000,3.304557e+06,4.000000,0.000000,0.000000,4.000000,...,11.000000,1.000000,56.000000,5.000000,0.000000,0.000000,0.000000,0.000000,663.000000,3.000000
max,168.000000,12.000000,2026.000000,43.000000,7.000000,9.999999e+06,43.000000,6.000000,9.000000,43.000000,...,419.000000,60.000000,370.000000,191.000000,112.000000,10.000000,4.000000,2.000000,3185.000000,3.000000

In [69]:
df.shape #quantidade de linhas e colunas

(37314, 65)

In [70]:
df.columns #retorna o nome de todas colunas

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [71]:
df.iloc[0:5]  #apresenta da 1a até a 5a linha

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [72]:
df_rj =df.loc[df['munic'] == 'Rio de Janeiro']  #retorna apenas dados do Rio de Janeiro
display(df_rj)

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37213,40,1,2026,2026m01,9,2,Rio de Janeiro,3304557,Capital,3,...,3.0,2.0,38,5,1,0,0,0,689,2
37214,41,1,2026,2026m01,18,2,Rio de Janeiro,3304557,Capital,2,...,5.0,0.0,37,3,1,0,0,0,858,2
37215,42,1,2026,2026m01,31,2,Rio de Janeiro,3304557,Capital,2,...,15.0,6.0,113,7,0,0,0,0,1444,2
37216,43,1,2026,2026m01,27,2,Rio de Janeiro,3304557,Capital,0,...,3.0,0.0,103,11,0,0,0,0,645,2
37217,44,1,2026,2026m01,3,1,Rio de Janeiro,3304557,Capital,1,...,12.0,0.0,32,3,0,0,0,0,853,2

In [73]:
df_capital_2020 = df.loc[(df['ano'] == 2020) & (df['regiao'] == 'Capital')]
df_capital_2020

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
27313,1,1,2020,2020m01,5,1,Rio de Janeiro,3304557,Capital,0,...,0.0,1.0,8,0,0,0,0,0,665,3
27314,4,1,2020,2020m01,5,1,Rio de Janeiro,3304557,Capital,1,...,15.0,13.0,10,3,0,0,0,0,600,3
27315,5,1,2020,2020m01,5,1,Rio de Janeiro,3304557,Capital,0,...,12.0,7.0,32,1,0,0,0,0,1193,3
27316,6,1,2020,2020m01,4,1,Rio de Janeiro,3304557,Capital,1,...,5.0,4.0,22,2,0,0,0,0,480,3
27317,7,1,2020,2020m01,5,1,Rio de Janeiro,3304557,Capital,0,...,1.0,1.0,10,0,0,0,0,0,161,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28856,40,12,2020,2020m12,9,2,Rio de Janeiro,3304557,Capital,2,...,3.0,0.0,22,2,0,0,0,0,420,3
28857,41,12,2020,2020m12,18,2,Rio de Janeiro,3304557,Capital,1,...,4.0,0.0,47,6,0,0,0,0,391,3
28858,42,12,2020,2020m12,31,2,Rio de Janeiro,3304557,Capital,0,...,8.0,1.0,81,2,0,0,0,0,745,3
28859,43,12,2020,2020m12,27,2,Rio de Janeiro,3304557,Capital,5,...,2.0,0.0,69,3,0,0,0,0,394,3
28860,44,12,2020,2020m12,3,1,Rio de Janeiro,3304557,Capital,2,...,25.0,0.0,19,2,1,0,0,0,487,3

In [74]:
df_2024 = df.loc[df['ano'] == 2024] #retorna apenas dados de 2024
print(df_2024)

       cisp  mes   ano  mes_ano  aisp  risp                 munic    mcirc  \
33889     1    1  2024  2024m01     5     1        Rio de Janeiro  3304557
33890     4    1  2024  2024m01     5     1        Rio de Janeiro  3304557
33891     5    1  2024  2024m01     5     1        Rio de Janeiro  3304557
33892     6    1  2024  2024m01     4     1        Rio de Janeiro  3304557
33893     7    1  2024  2024m01     5     1        Rio de Janeiro  3304557
...     ...  ...   ...      ...   ...   ...                   ...      ...
35528   159   12  2024  2024m12    35     4  Cachoeiras de Macacu  3300803
35529   165   12  2024  2024m12    33     5           Mangaratiba  3302601
35530   166   12  2024  2024m12    33     5        Angra dos Reis  3300100
35531   167   12  2024  2024m12    43     5                Paraty  3303807
35532   168   12  2024  2024m12    28     5             Rio Claro  3304409

         regiao  hom_doloso  ...   cmp  cmba  ameaca  pessoas_desaparecidas  \
33889   Capital           0  ...  16.0   4.0      12                      0
33890   Capital           0  ...   8.0   6.0      13                      3
33891   Capital           0  ...  12.0   2.0      46                      3
33892   Capital           0  ...   2.0   1.0      23                      2
33893   Capital           0  ...   0.0   0.0      12                      2
...         ...         ...  ...   ...   ...     ...                    ...
35528  Interior           1  ...   1.0   0.0      27                      2
35529  Interior           1  ...   6.0   0.0      31                      1
35530  Interior           0  ...  12.0   0.0      68                      5
35531  Interior           1  ...   2.0   0.0      17                      2
35532  Interior           0  ...   1.0   0.0       6                      0

       encontro_cadaver  encontro_ossada  pol_militares_mortos_serv  \
33889                 0                0                          0
33890                 0                0                          0
33891                 0                0                          0
33892                 0                0                          0
33893                 0                0                          0
...                 ...              ...                        ...
35528                 0                0                          0
35529                 1                0                          0
35530                 0                0                          0
35531                 1                0                          0
35532                 0                0                          0

       pol_civis_mortos_serv  registro_ocorrencias  fase
33889                      0                   889     3
33890                      0                   728     3
33891                      0                  1441     3
33892                      0                   650     3
33893                      0                   240     3
...                      ...                   ...   ...
35528                      0                   137     3
35529                      0                   209     3
35530                      0                   559     3
35531                      0                   223     3
35532                      0                    42     3

[1644 rows x 65 columns]

In [75]:
dados = np.array([12, 15, 17, 20, 22, 25, 28, 30, 35, 40])  #array é estrutura específica da biblioteca numpy
q1 = np.percentile(dados, 25)
q2 = np.percentile(dados, 50)
q3 = np.percentile(dados, 75)
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2): {q2}')
print(f'Terceiro quartil (Q3): {q3}')

Primeiro quartil (Q1): 17.75
Segundo quartil (Q2): 23.5
Terceiro quartil (Q3): 29.5

In [76]:
array_furto_celular = np.array(df_furto_celular_cisp['furto_celular'])
q1_furto_celular = np.percentile(array_furto_celular, 25)
q2_furto_celular = np.percentile(array_furto_celular, 50)
q3_furto_celular = np.percentile(array_furto_celular, 75)
media = np.mean(array_furto_celular)
mediana = np.median(array_furto_celular)
distancia = (media - mediana) / mediana
print(f'Primeiro quartil (Q1): {q1_furto_celular}')
print(f'Segundo quartil (Q2): {q2_furto_celular}')
print(f'Terceiro quartil (Q3): {q3_furto_celular}')
print(f'O valor de média é {media}')
print(f'O valor da mediana é {mediana}')
print(f'A distancia entre média e mediana é de {distancia}')

Primeiro quartil (Q1): 451.25
Segundo quartil (Q2): 1675.5
Terceiro quartil (Q3): 4580.0
O valor de média é 3422.978260869565
O valor da mediana é 1675.5
A distancia entre média e mediana é de 1.042959272378135

In [77]:
df_menor_q1_furto_celular = df_furto_celular_cisp.loc[df_furto_celular_cisp['furto_celular'] < q1_furto_celular]
df_menor_q1_furto_celular = df_menor_q1_furto_celular.sort_values(by='furto_celular', ascending=False)
df_menor_q1_furto_celular

     cisp  furto_celular
99    121            450
90    107            446
84     99            435
85    100            401
7      11            392
60     67            372
79     94            367
115   139            364
86    101            356
111   135            355
113   137            303
98    120            299
127   153            254
108   130            242
82     97            233
95    112            211
61     70            202
100   122            202
124   148            195
116   140            165
123   147            165
132   158            154
92    109            143
118   142            128
137   168            121
126   152            109
130   156            109
83     98             90
94    111             82
41     45             73
87    104             72
77     92             65
131   157             55
114   138             53
129   155             47

In [ ]:
df_regiao_metropolitana = df.loc[(df['municip'] == 'Rio de Janeiro') & (df['municip'] == 'Capital')]
df_capital_2020df_furto_celular_regiaoMetropolitana = df.groupby(municip)

In [ ]:
df_apreensao_menor_cisp = df.groupby('cisp')['aaapai'].sum().reset_index()  #qual apreensao de menor por delegacia?
display(df_apreensao_menor_cisp)
array_apreensao_menor = np.array(df_apreensao_menor_cisp['aaapai'])
q1_apreensao_menor = np.percentile(array_apreensao_menor, 25)
q2_apreensao_menor = np.percentile(array_apreensao_menor, 50)
q3_apreensao_menor = np.percentile(array_apreensao_menor, 75)
print(f'Primeiro quartil (Q1): {q1_apreensao_menor}')
print(f'Segundo quartil (Q2): {q2_apreensao_menor}')
print(f'Terceiro quartil (Q3): {q3_apreensao_menor}')
df_maior_apreensao_menor = df_apreensao_menor_cisp.loc[df_apreensao_menor_cisp['aaapai'] > q3_apreensao_menor]
df_maior_apreensao_menor

In [ ]:
df_aaapai_cap_2020 = df_capital_2020.groupby('cisp')['aaapai'].sum().reset_index()
df_aaapai_cap_2020 = df_aaapai_cap_2020.sort_values(by='aaapai', ascending=False)
df_aaapai_cap_2020

In [ ]:
gestao_atual = [2023,2024,2025,2026]
df_interior_atual = df.loc[(df['regiao'] == 'Interior') & (df['ano']).isin(gestao_atual)]  #isin busca dados dentro da lista
df_interior_atual

In [ ]:
#furto celular em 2024 na regiao metropolitana estado Rio de Janeiro
regiao_metropolitana = [
    'Rio de Janeiro','Niterói','São Gonçalo','Duque de Caxias', 
    'Nova Iguaçu', 'Belford Roxo','São João de Meriti', 
    'Nilópolis','Mesquita', 'Itaguaí', 'Magé', 'Guapimirim',
    'Paracambi','Queimaos','Seropédica','Tanguá','Rio Bonito','Cachoeiras de Macacu']
print(regiao_metropolitana)

In [85]:
df_rm_24 = df.loc[(df['ano'] ==2024) & (df['munic'].isin(regiao_metropolitana))]  #rm regiao metropolitana

In [92]:
df_furto_cel_rm_24 = df_rm_24.groupby('cisp')['furto_celular'].sum().reset_index()

array_furto_celular = np.array(df_furto_cel_rm_24['furto_celular'])
media = np.mean(array_furto_celular)
mediana = np.median(array_furto_celular)
distancia = (media-mediana) / mediana
print(f'O valor de média é {media}')
print(f'O valor de mediana é {mediana}')
print(f'A distância entre média e mediana é de {round(distancia,2) * 100}%')

O valor de média é 482.8857142857143
O valor de mediana é 242.5
A distância entre média e mediana é de 99.0%

In [ ]:
munic = df.groupby('munic').size().reset_index(name='quantidade') #contar os municipios
munic