In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('vendas_vestuario_revisao.csv')
df

   vendedor          produto  quantidade  valor_unitario
0   Edmundo    Camisa Social           2          217.87
1     Marta          Legging           2           76.57
2   Roberto      Calça Jeans           4          177.24
3   Roberto  Camiseta Básica           3           74.81
4    Junior          Legging           6          172.72
..      ...              ...         ...             ...
95  Roberto      Camisa Polo           3          145.74
96    Marta   Vestido Casual           2          207.33
97    Marta   Vestido Casual           4          236.13
98    Dulce    Jaqueta Jeans           4          384.26
99    Marta          Legging           4          114.32

[100 rows x 4 columns]

In [ ]:
df['Valor Vendido'] = df['quantidade']*df['valor_unitario'] #cria coluna na tabela 
df

In [ ]:
df_valor_vendido_vendedor = df.groupby('vendedor')['Valor Vendido'].sum().reset_index()  #grupando dados do vendedor por valor vendido
df_valor_vendido_vendedor

  vendedor  Valor Vendido
0    Dulce       16849.41
1  Edmundo       10438.38
2   Junior       13575.26
3    Marta       17816.03
4  Roberto       11801.67